### PR TITLE
Add some explanations to invariant theory code

### PR DESCRIPTION
**Pull request by joschmitt**
I added some short descriptions to the code snippets from the invariant theory chapter.

I assume it is clear what e.g. 'Example 27' refers to?

CC @wdecker @Lax202

### CODE REVIEW

**Comment by HereAround** [comment]
Thank you @joschmitt.

Have you used `autogenerate.jl` to mirror the changes in the template with the autogenerated .md files?

https://github.com/oscar-system/book.oscar-system.org/pull/32 aims to integrate this step into the build step of the website. Once finished, you would only need to adjust the template. (The autogenerated files would likely disappear into the .gitignore.)

Unless super pressing, could we use this PR as a non-trivial test? I.e. we wait for https://github.com/oscar-system/book.oscar-system.org/pull/32 to be merged, and then verify that the new build step makes the desired changes to the autogenerated file? @aaruni96 can probably gauge better if this is needed/makes sense.

Otherwise, I am perfectly happy to merge as is.

**Comment by joschmitt** [comment]
Yes, I used the script to generate the actual file.
This is not urgent for me. I (or you) can also remove the second commit, then this would only change the template file.

**Comment by aaruni96** [comment]
I think it does not matter either way. Once the auto generation is turned on, it will replace everything, and we will remove all the autogenerated md files from git tracking. "keep this PR to compare" is equally valid as "merging the other PR made everything garbage on the website" as a test.

**Comment by joschmitt** [comment]
Let me know, if I should do anything here now that #32 is merged.

**Comment by HereAround** [comment]
If I read correctly, @aaruni96 is happy either way. So I will just merge now.

**Pull request merged**
