### PR TITLE
[number-theory] remove auxiliary_code

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by lkastner** [comment]
Here the `main.jl` is a little more relevant than in other examples, since it contains the instructions for `Tally`. Without `Tally` some examples will not work. So do you @thofma want to insert a short sentence on `Tally` somewhere?

**Comment by thofma** [comment]
Good point! I will update this PR. Btw, do I need to regenerate it myself or does it regenerate it automatically?

**Comment by aaruni96** [comment]
Have to manually regenerate for now, we will enable auto regeneration once the host has julia available (so, soon(tm)).

To explain: if you edit just the template file, the changes will show up "eventually" (when auto regeneration is turned on sometime next week). If you want your changes reflected immediately, you have to manually regenerate as part of the PR.

**Comment by aaruni96** [comment]
#32 is merged, you only need to update templates now.

**Comment by lkastner** [comment]
I made a suggestion for resolving the conflict that appeared now, by removing the `main.jl` and adding a sentence on `Tally` right before the example using it. @thofma

**Comment by thofma** [comment]
Thanks Lars!

**Pull request merged**
